# Generated by Django 4.0 on 2022-01-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0002_rename_evaluetion_reviewmodel_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='useful_review',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
